name: aegis_vault
description: "Aegis-Vault — Local-First AI Document Intelligence Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rust_lib_aegis_vault:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  flutter_riverpod: any
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  file_picker: any
  pdfx: any
  freezed_annotation: any
  json_annotation: any
  riverpod_annotation: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  integration_test:
    sdk: flutter
  build_runner: any
  isar_generator: 3.1.0+1
  riverpod_generator: any
  freezed: any
  json_serializable: any
  msix: any

flutter:
  uses-material-design: true

msix_config:
  display_name: Aegis Vault
  publisher_display_name: Kavach AI
  identity_name: KavachAI.AegisVault
  msix_version: 1.0.0.0
  logo_path: windows/runner/resources/app_icon.ico
